import { Roboto } from "next/font/google";
import "./globals.css";
import ToasterClient from "@/components/shared/toaster.client";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "Tri-Gardening",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  antialiased`}>
        {children}
        <ToasterClient />
      </body>
    </html>
  );
}
