import { Poppins } from "next/font/google";
import "./globals.css";

const poppin = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Tri-Gardening",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppin.className}  antialiased`}>{children}</body>
    </html>
  );
}
